name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff psycopg2-binary

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Run ruff (lint check)
        run: ruff check .

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: blog_lite_api.settings
          DATABASE_URL: postgres://user:password@localhost:5432/test_db
        run: python manage.py migrate --noinput

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: blog_lite_api.settings
          DATABASE_URL: postgres://user:password@localhost:5432/test_db
        run: python manage.py test

